"""
📋 COMPREHENSIVE HEALTH REPORT GENERATOR
Creates professional medical-style reports for patients

Combines:
- Patient demographics
- Clinical findings
- Risk assessment
- Personalized recommendations
"""

import json
from datetime import datetime
from typing import Dict, Any

class ComprehensiveReportGenerator:
    """Generates patient-friendly medical reports"""

    def create_medical_report(self, patient_id: int, patient_data: Dict, 
                            synthesis: Dict, recommendations: Dict) -> Dict[str, Any]:
        """
        Generate complete medical report

        Patient Profile:
        - ID, Age, Gender

        Clinical Assessment:
        - Findings summary
        - Affected systems
        - Risk level

        Recommendations:
        - Immediate actions
        - Lifestyle changes
        - Follow-up schedule
        """

        report = {
            "report_metadata": {
                "generated_date": datetime.now().isoformat(),
                "patient_id": patient_id,
                "report_type": "Comprehensive Health Diagnostic"
            },

            "patient_profile": {
                "age": patient_data.get("age", "Unknown"),
                "gender": patient_data.get("gender", "Unknown"),
                "age_group": self.get_age_group(patient_data.get("age", 40))
            },

            "clinical_assessment": {
                "overall_risk": synthesis.get("overall_risk_level", "Unknown"),
                "risk_score": synthesis.get("risk_score", 0),
                "key_findings": synthesis.get("key_findings", []),
                "affected_systems": synthesis.get("affected_systems", []),
                "synthesis_summary": synthesis.get("synthesis_summary", "")
            },

            "health_recommendations": {
                "priority_actions": recommendations.get("priority_actions", []),
                "lifestyle_modifications": recommendations.get("lifestyle_modifications", []),
                "focus_areas": recommendations.get("age_appropriate_focus", ""),
                "follow_up_schedule": recommendations.get("follow_up_schedule", {})
            },

            "patient_summary": self.generate_patient_summary(
                synthesis, recommendations
            ),

            "disclaimer": (
                "This report is generated by an AI health diagnostics system. "
                "It is NOT a substitute for professional medical advice. "
                "Please consult with a qualified healthcare provider for diagnosis and treatment."
            )
        }

        return report

    def get_age_group(self, age: int) -> str:
        if age <= 35: return "Young Adult (18-35)"
        if age <= 50: return "Middle Adult (36-50)"
        if age <= 65: return "Senior (51-65)"
        return "Elderly (65+)"

    def generate_patient_summary(self, synthesis: Dict, recommendations: Dict) -> str:
        """Generate easy-to-read summary"""
        risk = synthesis.get("overall_risk_level", "Unknown")
        findings_count = len(synthesis.get("key_findings", []))
        systems = ", ".join(synthesis.get("affected_systems", ["N/A"]))

        if risk == "High" or risk == "Critical":
            urgency = "URGENT medical consultation recommended within 2 weeks."
        elif risk == "Medium":
            urgency = "Schedule medical appointment within 1 month."
        else:
            urgency = "Routine follow-up recommended annually."

        summary = (
            f"This patient presents with {findings_count} clinical findings affecting {systems} systems. "
            f"Overall risk assessment is {risk}. {urgency}"
        )

        return summary

# TEST
if __name__ == "__main__":
    gen = ComprehensiveReportGenerator()

    patient_data = {"age": 55, "gender": "Male"}
    synthesis = {
        "patient_context": patient_data,
        "key_findings": ["Elevated glucose", "High cholesterol"],
        "affected_systems": ["Metabolic", "Cardiovascular"],
        "overall_risk_level": "High",
        "risk_score": 6,
        "synthesis_summary": "Multiple metabolic and cardiovascular risks identified"
    }
    recommendations = {
        "priority_actions": ["Schedule urgent consultation"],
        "lifestyle_modifications": ["Reduce sugar", "Exercise daily"],
        "age_appropriate_focus": "Focus on cardiovascular fitness",
        "follow_up_schedule": {"consultation": "Within 2 weeks"}
    }

    report = gen.create_medical_report(1, patient_data, synthesis, recommendations)
    print("\n=== COMPREHENSIVE REPORT ===")
    print(json.dumps(report, indent=2))
